<?php

class Operaciones
{

    const NOTAS_DE_ENFERMERIA = 1;
    const MODIFICAR_NOTAS_DE_ENFERMERIAS = 2;
    const MODIFICAR_FECHAS = 3;
    const IMPRIMIR_NOTAS_DE_ENFERMERIA = 4;
    const CONTROLES_MEDICOS = 5;
    const EPICRISIS = 6;
    const REQUISICION_DE_MEDICAMENTOS = 7;
    const RECETAS = 8;
    const MODIFICAR_CONTROLES_MEDICOS = 9;
    const ADMISION_DE_PACIENTE = 10;
    const MODIFICAR_PACIENTES = 11;
    const MODIFICAR_ORDENES_MEDICAS = 12;
    const CREAR_SERVICIOS = 13;
    const MODIFICAR_FECHAS_RECETAS = 14;
    const FACTURAS_PARTICULARES = 15;
	const HISTORIA_CLINICA = 16;
}